document.addEventListener('DOMContentLoaded',()=>{
const navbar=document.querySelector('.navbar');let lastScrollY=0;
window.addEventListener('scroll',()=>{const cur=window.scrollY;if(cur>lastScrollY&&cur>200)navbar.classList.add('hidden');else navbar.classList.remove('hidden');lastScrollY=cur;const backBtn=document.querySelector('.back-to-top');if(backBtn){if(cur>500)backBtn.classList.add('visible');else backBtn.classList.remove('visible')}},{passive:true});
const navToggle=document.querySelector('.nav-toggle');const navLinks=document.querySelector('.nav-links');
if(navToggle){navToggle.addEventListener('click',()=>navLinks.classList.toggle('open'))}
document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>navLinks.classList.remove('open')));
document.querySelectorAll('.copy-btn').forEach(btn=>{btn.addEventListener('click',function(){const code=this.closest('.code-block').querySelector('pre').textContent;navigator.clipboard.writeText(code).then(()=>{this.textContent='已复制 ✓';this.style.borderColor='#137333';this.style.color='#137333';setTimeout(()=>{this.textContent='复制代码';this.style.borderColor='';this.style.color=''},2000)}).catch(()=>{const ta=document.createElement('textarea');ta.value=code;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();document.execCommand('copy');document.body.removeChild(ta);this.textContent='已复制 ✓';setTimeout(()=>{this.textContent='复制代码'},2000)})})});
const container=document.querySelector('.hero-particles');if(container){for(let i=0;i<25;i++){const p=document.createElement('div');p.className='particle';const s=Math.random()*4+2;p.style.width=s+'px';p.style.height=s+'px';p.style.left=Math.random()*100+'%';p.style.top=Math.random()*100+'%';p.style.animationDelay=Math.random()*20+'s';p.style.animationDuration=(Math.random()*15+15)+'s';container.appendChild(p)}}
const animEls=document.querySelectorAll('.vuln-card,.stat-card');if('IntersectionObserver'in window){const obs=new IntersectionObserver((entries)=>{entries.forEach(e=>{if(e.isIntersecting){e.target.style.opacity='1';e.target.style.transform='translateY(0)';obs.unobserve(e.target)}})},{threshold:0.1});animEls.forEach(el=>{el.style.opacity='0';el.style.transform='translateY(30px)';el.style.transition='opacity 0.6s ease,transform 0.6s ease';obs.observe(el)})}else{animEls.forEach(el=>{el.style.opacity='1';el.style.transform='translateY(0)'})}
document.querySelectorAll('a[href^="#"]').forEach(a=>{a.addEventListener('click',function(e){const href=this.getAttribute('href');if(href==='#')return;const target=document.querySelector(href);if(target){e.preventDefault();window.scrollTo({top:target.getBoundingClientRect().top+window.pageYOffset-70,behavior:'smooth'})}})});
console.log('💀 Command Injection Audit — 页面加载完成')});
